replicaCount: 2

image:
  nodeapp:
    repository: ylonkar/nodeapp
    tag: "latest"
  reactapp:
    repository: ylonkar/reactapp
    tag: "latest"
  pullPolicy: Always

service:
  reactapp:
    name: reactapp-service
    type: NodePort
    protocol: TCP
    externalPort: 80
    internalPort: 80
  nodeapp:
    name: nodeapp-service
    type: NodePort
    protocol: TCP
    externalPort: 80
    internalPort: 80

ingress:
  reactapp:
    name: react-ingress

resources:
  staticIp: reactapp

nodeSelector: {}

tolerations: []

affinity: {}