
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.resources.staticIp }}
spec:
  backend:
    serviceName: {{ .Values.service.name }}
    servicePort: {{ .Values.service.externalPort }}