apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.mongo.serviceName }}
  labels:
    app: mongodb
    chart: {{ template "nodeapp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    role: mongo